taiga.host=https://api.taiga.io
taiga.username=USERNAME
taiga.password=PASSWORD

GROQ_API_KEY=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
GROQ_BASE_URL=https://api.groq.com/openai/v1/chat/completions
GROQ_MODEL=llama-3.1-8b-instant
